version: 0.2

phases:

  pre_build:

    commands:
      - echo Logging in to Amazon ECR...
      - aws --version

      - $(aws ecr get-login --no-include-email)

      #- TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - TAG="latest"

      - ls -al
  build:

    commands:

      - docker build --tag "323080756126.dkr.ecr.us-east-2.amazonaws.com/cicd-ecr-2020-z:${TAG}" .

  post_build:

    commands:

      - docker push "323080756126.dkr.ecr.us-east-2.amazonaws.com/cicd-ecr-2020-z:${TAG}"

      - printf '{"tag":"%s"}' $TAG > build.json

artifacts:

  files: 
  - build.json
  - service.yaml
